/**
 * Comprehensive MEB & ÖSYM Curriculum Category Catalog for OdivonSchool.
 * id is used directly as the Firestore document ID (slug).
 */
const CATEGORIES = [
  // ==========================================
  // 1. İLKOKUL (1, 2, 3 ve 4. Sınıflar)
  // ==========================================
  // Matematik
  {
    id: 'ilkokul-matematik-dogal-sayilar',
    level: 'ilkokul',
    subject: 'Matematik',
    topic: 'Doğal Sayılar ve Basamak Değeri',
    description: 'Basamak adları, sayı ve basamak değerleri, çözümleme ve yuvarlama.',
    order: 1,
  },
  {
    id: 'ilkokul-matematik-toplama-cikarma',
    level: 'ilkokul',
    subject: 'Matematik',
    topic: 'Toplama ve Çıkarma İşlemleri',
    description: 'Eldeli toplama, onluk bozarak çıkarma ve zihinden işlemler.',
    order: 2,
  },
  {
    id: 'ilkokul-matematik-carpma-bolme',
    level: 'ilkokul',
    subject: 'Matematik',
    topic: 'Çarpma ve Bölme İşlemleri',
    description: 'Kısa yoldan çarpma, kalanlı bölme ve çarpım tablosu pratikleri.',
    order: 3,
  },
  {
    id: 'ilkokul-matematik-kesirler',
    level: 'ilkokul',
    subject: 'Matematik',
    topic: 'Kesirler ve Kesir Çeşitleri',
    description: 'Birim kesir, basit, bileşik, tam sayılı kesirler ve modelleme.',
    order: 4,
  },
  {
    id: 'ilkokul-matematik-geometri',
    level: 'ilkokul',
    subject: 'Matematik',
    topic: 'Geometrik Cisimler ve Şekiller',
    description: 'Küp, prizma, üçgen, kare, dikdörtgen ve simetri kuralları.',
    order: 5,
  },
  {
    id: 'ilkokul-matematik-olcmeler-ve-paralar',
    level: 'ilkokul',
    subject: 'Matematik',
    topic: 'Zaman, Uzunluk ve Para Ölçüleri',
    description: 'Saat okuma, zaman hesapları, metre-santimetre ve lira-kuruş problemleri.',
    order: 6,
  },

  // Türkçe
  {
    id: 'ilkokul-turkce-okudugunu-anlama',
    level: 'ilkokul',
    subject: 'Türkçe',
    topic: 'Okuduğunu Anlama ve Yorumlama',
    description: 'Metin analizi, ana fikir, başlık belirleme ve 5N1K soruları.',
    order: 7,
  },
  {
    id: 'ilkokul-turkce-es-zit-anlam',
    level: 'ilkokul',
    subject: 'Türkçe',
    topic: 'Eş ve Zıt Anlamlı Sözcükler',
    description: 'Anlamdaş kelimeler, karşıt anlamlılar ve eş sesli (sesteş) sözcükler.',
    order: 8,
  },
  {
    id: 'ilkokul-turkce-yazim-noktalama',
    level: 'ilkokul',
    subject: 'Türkçe',
    topic: 'Yazım Kuralları ve Noktalama',
    description: 'Büyük harf kullanımı, soru eki -mi, de/da yazımı ve noktalama işaretleri.',
    order: 9,
  },
  {
    id: 'ilkokul-turkce-atasozleri-deyimler',
    level: 'ilkokul',
    subject: 'Türkçe',
    topic: 'Atasözleri ve Deyimler',
    description: 'Türkçemizin zengin deyimleri, atasözlerinin anlamları ve mecaz anlatım.',
    order: 10,
  },

  // Fen Bilimleri
  {
    id: 'ilkokul-fen-yer-kabugu-ve-dunya',
    level: 'ilkokul',
    subject: 'Fen Bilimleri',
    topic: "Yer Kabuğu ve Dünya'mızın Hareketleri",
    description: 'Kayaçlar, madenler, fosiller, Dünya’nın dönme ve dolanma hareketleri.',
    order: 11,
  },
  {
    id: 'ilkokul-fen-besinlerimiz',
    level: 'ilkokul',
    subject: 'Fen Bilimleri',
    topic: 'Besinlerimiz ve Sağlıklı Yaşam',
    description: 'Proteinler, karbonhidratlar, vitaminler ve dengeli beslenme kuralları.',
    order: 12,
  },
  {
    id: 'ilkokul-fen-kuvvet-ve-hareket',
    level: 'ilkokul',
    subject: 'Fen Bilimleri',
    topic: 'Kuvvetin Etkileri ve Hareket',
    description: 'İtme-çekme kuvveti, hızlanma, yavaşlama, yön değiştirme ve mıknatıslar.',
    order: 13,
  },
  {
    id: 'ilkokul-fen-maddenin-halleri',
    level: 'ilkokul',
    subject: 'Fen Bilimleri',
    topic: 'Maddenin Özellikleri ve Halleri',
    description: 'Katı, sıvı, gaz maddeler, suda yüzen-batan maddeler ve saf madde-karışım.',
    order: 14,
  },

  // Hayat Bilgisi & Sosyal Bilgiler
  {
    id: 'ilkokul-sosyal-birey-ve-toplum',
    level: 'ilkokul',
    subject: 'Sosyal Bilgiler',
    topic: 'Birey ve Toplum: Haklarımız',
    description: 'Kimlik kartı, resmi belgeler, hak ve sorumluluklarımız, empati.',
    order: 15,
  },
  {
    id: 'ilkokul-sosyal-kultur-ve-miras',
    level: 'ilkokul',
    subject: 'Sosyal Bilgiler',
    topic: 'Kültürümüz ve Milli Mirasımız',
    description: 'Aile tarihi, geleneksel oyunlar, milli bayramlar ve kültürel değerler.',
    order: 16,
  },

  // ==========================================
  // 2. ORTAOKUL (5, 6, 7, 8. Sınıflar & LGS)
  // ==========================================
  // Matematik (LGS)
  {
    id: 'ortaokul-matematik-carpanlar-katlar',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Çarpanlar ve Katlar (EBOB - EKOK)',
    description: 'Asal çarpanlara ayırma, EBOB ve EKOK problemleri, aralarında asal sayılar.',
    order: 1,
  },
  {
    id: 'ortaokul-matematik-uslu-ifadeler',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Üslü İfadeler ve Bilimsel Gösterim',
    description: 'Tam sayıların kuvvetleri, üslü sayılarda işlemler ve çok büyük/küçük sayılar.',
    order: 2,
  },
  {
    id: 'ortaokul-matematik-karekoklu-ifadeler',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Kareköklü İfadeler',
    description: 'Tam kare sayılar, kareköklü sayılarda çarpma, bölme, toplama ve çıkarma.',
    order: 3,
  },
  {
    id: 'ortaokul-matematik-olasilik-ve-veri',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Veri Analizi ve Basit Olayların Olasılığı',
    description: 'Daire, sütun, çizgi grafikleri ve olası durumları hesaplama.',
    order: 4,
  },
  {
    id: 'ortaokul-matematik-cebir-ve-ozdeslikler',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Cebirsel İfadeler ve Özdeşlikler',
    description: 'Terimler, katsayılar, tam kare özdeşlikler ve iki kare farkı.',
    order: 5,
  },
  {
    id: 'ortaokul-matematik-denklemler-ve-grafikler',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Doğrusal Denklemler ve Eğim',
    description: 'Birinci dereceden bir bilinmeyenli denklemler, koordinat sistemi ve eğim.',
    order: 6,
  },
  {
    id: 'ortaokul-matematik-esitsizlikler',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Birinci Dereceden Eşitsizlikler',
    description: 'Eşitsizlik kurma, sayı doğrusunda gösterme ve eşitsizlik çözümü.',
    order: 7,
  },
  {
    id: 'ortaokul-matematik-ucgenler-ve-pisagor',
    level: 'ortaokul',
    subject: 'Matematik',
    topic: 'Üçgenler ve Pisagor Bağıntısı',
    description: 'Açıortay, kenarortay, üçgen eşitsizliği ve dik üçgende Pisagor teoremi.',
    order: 8,
  },

  // Türkçe (LGS)
  {
    id: 'ortaokul-turkce-fiilimsiler',
    level: 'ortaokul',
    subject: 'Türkçe',
    topic: 'Fiilimsiler (Eylemsiler)',
    description: 'İsim-fiil, sıfat-fiil, zarf-fiil ekleri ve cümledeki görevleri.',
    order: 9,
  },
  {
    id: 'ortaokul-turkce-sozcuk-cumle-anlam',
    level: 'ortaokul',
    subject: 'Türkçe',
    topic: 'Sözcük ve Cümlede Anlam',
    description: 'Gerçek, mecaz, terim anlam, neden-sonuç, amaç-sonuç ve örtülü anlam.',
    order: 10,
  },
  {
    id: 'ortaokul-turkce-paragraf-ve-ana-fikir',
    level: 'ortaokul',
    subject: 'Türkçe',
    topic: 'Paragrafta Anlam ve Yapı',
    description: 'Ana fikir, yardımcı fikirler, akışı bozan cümle ve metin tamamlama.',
    order: 11,
  },
  {
    id: 'ortaokul-turkce-cumlenin-ogeleri',
    level: 'ortaokul',
    subject: 'Türkçe',
    topic: 'Cümlenin Ögeleri ve Cümle Türleri',
    description: 'Yüklem, özne, nesne, yer tamlayıcısı, zarf tamlayıcısı ve fiil çatıları.',
    order: 12,
  },
  {
    id: 'ortaokul-turkce-sozel-mantik',
    level: 'ortaokul',
    subject: 'Türkçe',
    topic: 'Sözel Mantık ve Muhakeme',
    description: 'Tablo ve grafik okuma, sıralama, yerleştirme ve çıkarım soruları.',
    order: 13,
  },

  // Fen Bilimleri (LGS)
  {
    id: 'ortaokul-fen-mevsimler-ve-iklim',
    level: 'ortaokul',
    subject: 'Fen Bilimleri',
    topic: 'Mevsimler ve İklim',
    description: 'Dünya’nın eksen eğikliği, mevsimlerin oluşumu, iklim ve hava hareketleri.',
    order: 14,
  },
  {
    id: 'ortaokul-fen-dna-ve-genetik-kod',
    level: 'ortaokul',
    subject: 'Fen Bilimleri',
    topic: 'DNA ve Genetik Kod',
    description: 'DNA yapısı ve eşlenmesi, kalıtım, mutasyon, modifikasyon ve biyoteknoloji.',
    order: 15,
  },
  {
    id: 'ortaokul-fen-basinc',
    level: 'ortaokul',
    subject: 'Fen Bilimleri',
    topic: 'Basınç (Katı, Sıvı ve Gaz)',
    description: 'Katı basıncı, sıvı basıncı (Pascal prensibi), açık hava basıncı ve uygulamaları.',
    order: 16,
  },
  {
    id: 'ortaokul-fen-madde-ve-endustri',
    level: 'ortaokul',
    subject: 'Fen Bilimleri',
    topic: 'Madde ve Endüstri (Asitler & Bazlar)',
    description: 'Periyodik sistem, fiziksel ve kimyasal değişimler, asit-baz tepkimeleri.',
    order: 17,
  },
  {
    id: 'ortaokul-fen-basit-makineler',
    level: 'ortaokul',
    subject: 'Fen Bilimleri',
    topic: 'Basit Makineler',
    description: 'Kaldıraçlar, makaralar, palangalar, eğik düzlem, vida, kasnak ve dişliler.',
    order: 18,
  },

  // İnkılap Tarihi
  {
    id: 'ortaokul-inkilap-milli-uyanis',
    level: 'ortaokul',
    subject: 'T.C. İnkılap Tarihi',
    topic: 'Milli Uyanış ve Kurtuluş Savaşı',
    description: 'I. Dünya Savaşı, genelgeler, kongreler, TBMM’nin açılışı ve cepheler.',
    order: 19,
  },
  {
    id: 'ortaokul-inkilap-ataturkculuk-ve-ilkeler',
    level: 'ortaokul',
    subject: 'T.C. İnkılap Tarihi',
    topic: 'Atatürk İlkeleri ve İnkılapları',
    description: 'Cumhuriyetçilik, Milliyetçilik, Halkçılık, Laiklik, Devletçilik, İnkılapçılık.',
    order: 20,
  },

  // ==========================================
  // 3. LİSE (9, 10, 11, 12. Sınıf & YKS TYT/AYT)
  // ==========================================
  // Matematik (TYT / AYT)
  {
    id: 'lise-matematik-temel-kavramlar',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Temel Kavramlar ve Sayı Kümeleri (TYT)',
    description: 'Doğal sayılar, tam sayılar, asal sayılar, faktöriyel ve basamak analizi.',
    order: 1,
  },
  {
    id: 'lise-matematik-bolunebilme-ebob-ekok',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Bölünebilme Kuralları ve EBOB-EKOK (TYT)',
    description: 'Bölünebilme kuralları, periyodik durumlar ve EBOB-EKOK uygulamaları.',
    order: 2,
  },
  {
    id: 'lise-matematik-uslu-koklu-sayilar',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Üslü ve Köklü Sayılar (TYT)',
    description: 'Üslü denklemler, köklü ifadeler ve eşlenik ile genişletme.',
    order: 3,
  },
  {
    id: 'lise-matematik-problemler',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Oran-Orantı ve Yeni Nesil Problemler (TYT)',
    description: 'Sayı, kesir, yaş, işçi, hız, yüzde, kâr-zarar ve karışım problemleri.',
    order: 4,
  },
  {
    id: 'lise-matematik-fonksiyonlar',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Fonksiyonlar ve Fonksiyon Grafikleri (TYT/AYT)',
    description: 'Birebir, örten fonksiyonlar, ters fonksiyon, bileşke ve fonksiyon grafikleri.',
    order: 5,
  },
  {
    id: 'lise-matematik-polinomlar-ve-denklemler',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Polinomlar ve 2. Dereceden Denklemler (AYT)',
    description: 'Polinomlarda bölme, kök-katsayı ilişkisi ve karmaşık sayılar.',
    order: 6,
  },
  {
    id: 'lise-matematik-trigonometri',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Trigonometri (AYT)',
    description: 'Birim çember, trigonometrik fonksiyonlar, toplam-fark ve yarım açı formülleri.',
    order: 7,
  },
  {
    id: 'lise-matematik-logaritma-ve-diziler',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Logaritma ve Diziler (AYT)',
    description: 'Üstel fonksiyon, logaritma özellikleri, aritmetik ve geometrik diziler.',
    order: 8,
  },
  {
    id: 'lise-matematik-limit-ve-sureklilik',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Limit ve Süreklilik (AYT)',
    description: 'Sağdan-soldan limit, 0/0 belirsizliği ve süreklilik kuralları.',
    order: 9,
  },
  {
    id: 'lise-matematik-turev-uygulamalari',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Türev ve Uygulamaları (AYT)',
    description: 'Türev alma kuralları, teğet denklemi, artan-azalanlık, yerel ekstremum.',
    order: 10,
  },
  {
    id: 'lise-matematik-integral',
    level: 'lise',
    subject: 'Matematik',
    topic: 'Belirli ve Belirsiz İntegral (AYT)',
    description: 'İntegral alma teknikleri, değişken değiştirme ve eğri altında kalan alan hesabı.',
    order: 11,
  },

  // Fizik (TYT / AYT)
  {
    id: 'lise-fizik-kuvvet-ve-hareket',
    level: 'lise',
    subject: 'Fizik',
    topic: 'Kuvvet, Hareket ve Newton Yasaları (TYT/AYT)',
    description: 'Düzgün doğrusal hareket, ivmeli hareket, dinamik ve sürtünme kuvveti.',
    order: 12,
  },
  {
    id: 'lise-fizik-is-guc-enerji',
    level: 'lise',
    subject: 'Fizik',
    topic: 'İş, Güç ve Mekanik Enerji (TYT)',
    description: 'Kinetik enerji, potansiyel enerji, sürtünmeli ortamlarda mekanik enerji korunumu.',
    order: 13,
  },
  {
    id: 'lise-fizik-elektrik-ve-manyetizma',
    level: 'lise',
    subject: 'Fizik',
    topic: 'Elektrik Akımı ve Manyetizma (AYT)',
    description: 'Ohm kanunu, devreler, manyetik alan, manyetik kuvvet ve indüksiyon akımı.',
    order: 14,
  },
  {
    id: 'lise-fizik-optik-ve-dalgalar',
    level: 'lise',
    subject: 'Fizik',
    topic: 'Optik ve Dalga Mekaniği (TYT/AYT)',
    description: 'Aydınlanma, yansıma, aynalar, kırılma, mercekler ve çift yarıkta girişim.',
    order: 15,
  },

  // Kimya (TYT / AYT)
  {
    id: 'lise-kimya-atom-ve-periyodik-sistem',
    level: 'lise',
    subject: 'Kimya',
    topic: 'Atom Modelleri ve Periyodik Sistem (TYT)',
    description: 'Proton, nötron, elektron, periyodik özelliklerin değişimi ve kimyasal türler.',
    order: 16,
  },
  {
    id: 'lise-kimya-kimyasal-hesaplamalar',
    level: 'lise',
    subject: 'Kimya',
    topic: 'Mol Kavramı ve Kimyasal Tepkimeler (TYT)',
    description: 'Mol hesapları, tepkime denklemleri, sınırlayıcı bileşen ve verim hesapları.',
    order: 17,
  },
  {
    id: 'lise-kimya-gazlar-ve-cozeltiler',
    level: 'lise',
    subject: 'Kimya',
    topic: 'Gaz Yasaları ve Sıvı Çözeltiler (AYT)',
    description: 'İdeal gaz denklemi, kısmi basınç, derişim birimleri ve koligatif özellikler.',
    order: 18,
  },
  {
    id: 'lise-kimya-organik-kimya',
    level: 'lise',
    subject: 'Kimya',
    topic: 'Organik Kimyaya Giriş ve Hidrokarbonlar (AYT)',
    description: 'Karbon allotropları, Lewis formülleri, hibritleşme, alkan, alken ve alkinler.',
    order: 19,
  },

  // Biyoloji (TYT / AYT)
  {
    id: 'lise-biyoloji-hucre-ve-organeller',
    level: 'lise',
    subject: 'Biyoloji',
    topic: 'Hücre Yapısı ve Madde Geçişleri (TYT)',
    description: 'Prokaryot-ökaryot hücre, organeller, difüzyon, osmoz ve aktif taşıma.',
    order: 20,
  },
  {
    id: 'lise-biyoloji-kalitim-ve-genetik',
    level: 'lise',
    subject: 'Biyoloji',
    topic: 'Mendel Kalıtımı ve Biyolojik Çeşitlilik (TYT)',
    description: 'Monohibrit-dihibrit çaprazlama, kan grupları, eşeye bağlı kalıtım ve soy ağaçları.',
    order: 21,
  },
  {
    id: 'lise-biyoloji-insan-fizyolojisi',
    level: 'lise',
    subject: 'Biyoloji',
    topic: 'İnsan Fizyolojisi ve Sistemler (AYT)',
    description: 'Sinir, endokrin, duyu organları, dolaşım, bağışıklık, solunum ve boşaltım sistemleri.',
    order: 22,
  },

  // Edebiyat & Tarih
  {
    id: 'lise-edebiyat-paragraf-ve-anlatim',
    level: 'lise',
    subject: 'Edebiyat',
    topic: 'Paragrafta Anlam ve Anlatım Teknikleri (TYT)',
    description: 'Ana düşünce, paragraf yapısı, anlatım biçimleri ve düşünceyi geliştirme yolları.',
    order: 23,
  },
  {
    id: 'lise-edebiyat-divan-ve-halk',
    level: 'lise',
    subject: 'Edebiyat',
    topic: 'Divan ve Halk Edebiyatı (AYT)',
    description: 'Nazım biçimleri, aruz ve hece ölçüsü, divan ve halk şairleri, edebi sanatlar.',
    order: 24,
  },
  {
    id: 'lise-tarih-osmanli-ve-kurtulus',
    level: 'lise',
    subject: 'Tarih',
    topic: 'Osmanlı Devleti ve Kurtuluş Savaşı Tarihi (TYT/AYT)',
    description: 'Osmanlı kurumları, diplomasi, I. Dünya Savaşı, Milli Mücadele ve inkılaplar.',
    order: 25,
  },

  // ==========================================
  // 4. KPSS (Genel Yetenek & Genel Kültür)
  // ==========================================
  // Genel Yetenek (Türkçe & Matematik)
  {
    id: 'kpss-genel-yetenek-sozel-mantik',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'Sözel Mantık ve Muhakeme',
    description: 'ÖSYM tarzı sıralama, eşleştirme, çıkarım ve tablo analizi soruları.',
    order: 1,
  },
  {
    id: 'kpss-genel-yetenek-paragraf',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'Paragrafta Anlam ve Anlatım',
    description: 'Hızlı okuma, ana düşünce tespiti, akışı bozan cümleler ve yardımcı fikirler.',
    order: 2,
  },
  {
    id: 'kpss-genel-yetenek-dil-bilgisi',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'Türkçe Dil Bilgisi ve Yazım Kuralları',
    description: 'Ses bilgisi, sözcük yapısı, anlatım bozuklukları, yazım ve noktalama kuralları.',
    order: 3,
  },
  {
    id: 'kpss-genel-yetenek-sayisal-mantik',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'Sayısal Mantık ve Akıl Yürütme',
    description: 'Örüntüler, şekil-grafik ilişkileri, modüler aritmetik ve problem kurguları.',
    order: 4,
  },
  {
    id: 'kpss-genel-yetenek-temel-matematik',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'Temel Matematik ve İşlem Yeteneği',
    description: 'Dört işlem, ardışık sayılar, faktöriyel, basamak kavramı ve rasyonel sayılar.',
    order: 5,
  },
  {
    id: 'kpss-genel-yetenek-problemler',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'KPSS Matematik Problemleri',
    description: 'Sayı-kesir, yaş, hareket, işçi-havuz, yüzde, faiz ve kâr-zarar problemleri.',
    order: 6,
  },
  {
    id: 'kpss-genel-yetenek-geometri',
    level: 'kpss',
    subject: 'Genel Yetenek',
    topic: 'Temel Geometri ve Ölçmeler',
    description: 'Doğruda ve üçgende açılar, özel üçgenler, dörtgenler, çember ve alan hesapları.',
    order: 7,
  },

  // Genel Kültür (Tarih, Coğrafya, Vatandaşlık, Güncel)
  {
    id: 'kpss-genel-kultur-ilk-turk-devletleri',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: 'İslamiyet Öncesi Türk Tarihi ve Selçuklular',
    description: 'Orta Asya Türk kültürü, ilk devletler, Türk-İslam sentezi ve Anadolu Selçuklu.',
    order: 8,
  },
  {
    id: 'kpss-genel-kultur-osmanli-tarihi',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: 'Osmanlı Tarihi ve Kültür Medeniyet',
    description: 'Osmanlı devlet teşkilatı, ordu, toprak sistemi, ıslahatlar ve çöküş dönemi.',
    order: 9,
  },
  {
    id: 'kpss-genel-kultur-inkilap-tarihi',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: 'Milli Mücadele ve Cumhuriyet Tarihi',
    description: 'Kongreler, Misak-ı Milli, Muharebeler, Lozan Antlaşması ve Atatürk inkılapları.',
    order: 10,
  },
  {
    id: 'kpss-genel-kultur-turkiye-fiziki-cografyasi',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: "Türkiye'nin Fiziki Coğrafyası ve İklimi",
    description: 'Türkiye’nin coğrafi konumu, yer şekilleri, dağlar, ovalar, akarsular ve iklim tipleri.',
    order: 11,
  },
  {
    id: 'kpss-genel-kultur-turkiye-beseri-cografyasi',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: "Türkiye'nin Beşeri ve Ekonomik Coğrafyası",
    description: 'Nüfus ve yerleşme dinamikleri, tarım, hayvancılık, madenler, sanayi ve ulaşım.',
    order: 12,
  },
  {
    id: 'kpss-genel-kultur-temel-hukuk',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: 'Temel Hukuk Kavramları',
    description: 'Hukukun kaynakları, normlar hiyerarşisi, hak kavramı, ehliyetler ve yaptırım türleri.',
    order: 13,
  },
  {
    id: 'kpss-genel-kultur-anayasa-hukuku',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: '1982 Anayasası: Yasama, Yürütme, Yargı',
    description: 'TBMM’nin görevleri, Cumhurbaşkanlığı kararnameleri, bakanlıklar ve yüksek mahkemeler.',
    order: 14,
  },
  {
    id: 'kpss-genel-kultur-idare-hukuku',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: 'İdare Hukuku ve Türkiye’nin İdari Yapısı',
    description: 'Merkezden yönetim, yerinden yönetim, valilik, belediyeler ve kamu görevlileri.',
    order: 15,
  },
  {
    id: 'kpss-genel-kultur-guncel-olaylar',
    level: 'kpss',
    subject: 'Genel Kültür',
    topic: 'Güncel Bilgiler ve Uluslararası Kuruluşlar',
    description: 'BM, NATO, AB gibi örgütler, Türkiye’nin uluslararası ilişkileri ve güncel kültür olayları.',
    order: 16,
  },
];

module.exports = { CATEGORIES };
